version: '2'
services:
    fhirmapping-app:
        image: fhirmapping
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fhirmapping-postgresql:5432/fhirMapping
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fhirmapping-postgresql:
        extends:
            file: postgresql.yml
            service: fhirmapping-postgresql
