//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.15 at 01:50:20 PM EDT 
//


package com.mapping.esource.fhirmapping.beans.gtp;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SpecimenCollection"/>
 *         &lt;element ref="{}SpecimenTransport" minOccurs="0"/>
 *         &lt;element ref="{}SpecimenComment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SpecimenMaterial" minOccurs="0"/>
 *         &lt;element ref="{}SubjectAtCollection" minOccurs="0"/>
 *         &lt;element ref="{}BaseBattery" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}TransactionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "specimenCollection",
    "specimenTransport",
    "specimenComment",
    "specimenMaterial",
    "subjectAtCollection",
    "baseBattery",
    "transactionType"
})
@XmlRootElement(name = "BaseSpecimen")
public class BaseSpecimen
    implements Serializable
{

    private final static long serialVersionUID = 5190875983846359311L;
    @XmlElement(name = "SpecimenCollection", required = true)
    protected SpecimenCollection specimenCollection;
    @XmlElement(name = "SpecimenTransport")
    protected SpecimenTransport specimenTransport;
    @XmlElement(name = "SpecimenComment")
    protected List<SpecimenComment> specimenComment;
    @XmlElement(name = "SpecimenMaterial")
    protected SpecimenMaterial specimenMaterial;
    @XmlElement(name = "SubjectAtCollection")
    protected SubjectAtCollection subjectAtCollection;
    @XmlElement(name = "BaseBattery")
    protected List<BaseBattery> baseBattery;
    @XmlElement(name = "TransactionType")
    protected String transactionType;
    @XmlAttribute(name = "ID")
    protected String id;

    /**
     * Gets the value of the specimenCollection property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenCollection }
     *     
     */
    public SpecimenCollection getSpecimenCollection() {
        return specimenCollection;
    }

    /**
     * Sets the value of the specimenCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenCollection }
     *     
     */
    public void setSpecimenCollection(SpecimenCollection value) {
        this.specimenCollection = value;
    }

    /**
     * Gets the value of the specimenTransport property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenTransport }
     *     
     */
    public SpecimenTransport getSpecimenTransport() {
        return specimenTransport;
    }

    /**
     * Sets the value of the specimenTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenTransport }
     *     
     */
    public void setSpecimenTransport(SpecimenTransport value) {
        this.specimenTransport = value;
    }

    /**
     * Gets the value of the specimenComment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specimenComment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecimenComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecimenComment }
     * 
     * 
     */
    public List<SpecimenComment> getSpecimenComment() {
        if (specimenComment == null) {
            specimenComment = new ArrayList<SpecimenComment>();
        }
        return this.specimenComment;
    }

    /**
     * Gets the value of the specimenMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link SpecimenMaterial }
     *     
     */
    public SpecimenMaterial getSpecimenMaterial() {
        return specimenMaterial;
    }

    /**
     * Sets the value of the specimenMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecimenMaterial }
     *     
     */
    public void setSpecimenMaterial(SpecimenMaterial value) {
        this.specimenMaterial = value;
    }

    /**
     * Gets the value of the subjectAtCollection property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectAtCollection }
     *     
     */
    public SubjectAtCollection getSubjectAtCollection() {
        return subjectAtCollection;
    }

    /**
     * Sets the value of the subjectAtCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectAtCollection }
     *     
     */
    public void setSubjectAtCollection(SubjectAtCollection value) {
        this.subjectAtCollection = value;
    }

    /**
     * Gets the value of the baseBattery property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseBattery property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseBattery().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseBattery }
     * 
     * 
     */
    public List<BaseBattery> getBaseBattery() {
        if (baseBattery == null) {
            baseBattery = new ArrayList<BaseBattery>();
        }
        return this.baseBattery;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
