//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.15 at 01:50:20 PM EDT 
//


package com.mapping.esource.fhirmapping.beans.gtp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mapping.esource.fhirmapping.beans.gtp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestLevelComment_QNAME = new QName("", "TestLevelComment");
    private final static QName _SpareSubjectID_QNAME = new QName("", "SpareSubjectID");
    private final static QName _SubjectID_QNAME = new QName("", "SubjectID");
    private final static QName _TransactionType_QNAME = new QName("", "TransactionType");
    private final static QName _ScreenID_QNAME = new QName("", "ScreenID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mapping.esource.fhirmapping.beans.gtp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpecimenCollection }
     * 
     */
    public SpecimenCollection createSpecimenCollection() {
        return new SpecimenCollection();
    }

    /**
     * Create an instance of {@link CentralLab }
     * 
     */
    public CentralLab createCentralLab() {
        return new CentralLab();
    }

    /**
     * Create an instance of {@link LabTest }
     * 
     */
    public LabTest createLabTest() {
        return new LabTest();
    }

    /**
     * Create an instance of {@link ResultUnits }
     * 
     */
    public ResultUnits createResultUnits() {
        return new ResultUnits();
    }

    /**
     * Create an instance of {@link ReceiverTest }
     * 
     */
    public ReceiverTest createReceiverTest() {
        return new ReceiverTest();
    }

    /**
     * Create an instance of {@link Confidential }
     * 
     */
    public Confidential createConfidential() {
        return new Confidential();
    }

    /**
     * Create an instance of {@link NumericResult }
     * 
     */
    public NumericResult createNumericResult() {
        return new NumericResult();
    }

    /**
     * Create an instance of {@link SingleResult }
     * 
     */
    public SingleResult createSingleResult() {
        return new SingleResult();
    }

    /**
     * Create an instance of {@link TextResult }
     * 
     */
    public TextResult createTextResult() {
        return new TextResult();
    }

    /**
     * Create an instance of {@link ResultReferenceRange }
     * 
     */
    public ResultReferenceRange createResultReferenceRange() {
        return new ResultReferenceRange();
    }

    /**
     * Create an instance of {@link LOINCTestCode }
     * 
     */
    public LOINCTestCode createLOINCTestCode() {
        return new LOINCTestCode();
    }

    /**
     * Create an instance of {@link Study }
     * 
     */
    public Study createStudy() {
        return new Study();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link Investigator }
     * 
     */
    public Investigator createInvestigator() {
        return new Investigator();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link Sex }
     * 
     */
    public Sex createSex() {
        return new Sex();
    }

    /**
     * Create an instance of {@link Race }
     * 
     */
    public Race createRace() {
        return new Race();
    }

    /**
     * Create an instance of {@link Visit }
     * 
     */
    public Visit createVisit() {
        return new Visit();
    }

    /**
     * Create an instance of {@link Accession }
     * 
     */
    public Accession createAccession() {
        return new Accession();
    }

    /**
     * Create an instance of {@link BaseSpecimen }
     * 
     */
    public BaseSpecimen createBaseSpecimen() {
        return new BaseSpecimen();
    }

    /**
     * Create an instance of {@link SpecimenTransport }
     * 
     */
    public SpecimenTransport createSpecimenTransport() {
        return new SpecimenTransport();
    }

    /**
     * Create an instance of {@link SpecimenComment }
     * 
     */
    public SpecimenComment createSpecimenComment() {
        return new SpecimenComment();
    }

    /**
     * Create an instance of {@link SpecimenMaterial }
     * 
     */
    public SpecimenMaterial createSpecimenMaterial() {
        return new SpecimenMaterial();
    }

    /**
     * Create an instance of {@link SubjectAtCollection }
     * 
     */
    public SubjectAtCollection createSubjectAtCollection() {
        return new SubjectAtCollection();
    }

    /**
     * Create an instance of {@link BaseBattery }
     * 
     */
    public BaseBattery createBaseBattery() {
        return new BaseBattery();
    }

    /**
     * Create an instance of {@link BaseTest }
     * 
     */
    public BaseTest createBaseTest() {
        return new BaseTest();
    }

    /**
     * Create an instance of {@link PerformingLab }
     * 
     */
    public PerformingLab createPerformingLab() {
        return new PerformingLab();
    }

    /**
     * Create an instance of {@link BaseResult }
     * 
     */
    public BaseResult createBaseResult() {
        return new BaseResult();
    }

    /**
     * Create an instance of {@link ToxicityGrade }
     * 
     */
    public ToxicityGrade createToxicityGrade() {
        return new ToxicityGrade();
    }

    /**
     * Create an instance of {@link TransmissionSource }
     * 
     */
    public TransmissionSource createTransmissionSource() {
        return new TransmissionSource();
    }

    /**
     * Create an instance of {@link GTP }
     * 
     */
    public GTP createGTP() {
        return new GTP();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TestLevelComment")
    public JAXBElement<String> createTestLevelComment(String value) {
        return new JAXBElement<String>(_TestLevelComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SpareSubjectID")
    public JAXBElement<String> createSpareSubjectID(String value) {
        return new JAXBElement<String>(_SpareSubjectID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubjectID")
    public JAXBElement<String> createSubjectID(String value) {
        return new JAXBElement<String>(_SubjectID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionType")
    public JAXBElement<String> createTransactionType(String value) {
        return new JAXBElement<String>(_TransactionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScreenID")
    public JAXBElement<String> createScreenID(String value) {
        return new JAXBElement<String>(_ScreenID_QNAME, String.class, null, value);
    }

}
