//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.15 at 01:50:20 PM EDT 
//


package com.mapping.esource.fhirmapping.beans.gtp;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TextResult" minOccurs="0"/>
 *         &lt;element ref="{}NumericResult" minOccurs="0"/>
 *         &lt;element ref="{}ResultReferenceRange" minOccurs="0"/>
 *         &lt;element ref="{}ResultUnits" minOccurs="0"/>
 *         &lt;element ref="{}TransactionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ResultClass" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="R"/>
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="S"/>
 *             &lt;maxLength value="12"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ResultType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="G"/>
 *             &lt;enumeration value="L"/>
 *             &lt;enumeration value="R"/>
 *             &lt;maxLength value="12"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textResult",
    "numericResult",
    "resultReferenceRange",
    "resultUnits",
    "transactionType"
})
@XmlRootElement(name = "SingleResult")
public class SingleResult
    implements Serializable
{

    private final static long serialVersionUID = 5190875983846359311L;
    @XmlElement(name = "TextResult")
    protected TextResult textResult;
    @XmlElement(name = "NumericResult")
    protected NumericResult numericResult;
    @XmlElement(name = "ResultReferenceRange")
    protected ResultReferenceRange resultReferenceRange;
    @XmlElement(name = "ResultUnits")
    protected ResultUnits resultUnits;
    @XmlElement(name = "TransactionType")
    protected String transactionType;
    @XmlAttribute(name = "ResultClass", required = true)
    protected String resultClass;
    @XmlAttribute(name = "ResultType", required = true)
    protected String resultType;

    /**
     * Gets the value of the textResult property.
     * 
     * @return
     *     possible object is
     *     {@link TextResult }
     *     
     */
    public TextResult getTextResult() {
        return textResult;
    }

    /**
     * Sets the value of the textResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextResult }
     *     
     */
    public void setTextResult(TextResult value) {
        this.textResult = value;
    }

    /**
     * Gets the value of the numericResult property.
     * 
     * @return
     *     possible object is
     *     {@link NumericResult }
     *     
     */
    public NumericResult getNumericResult() {
        return numericResult;
    }

    /**
     * Sets the value of the numericResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericResult }
     *     
     */
    public void setNumericResult(NumericResult value) {
        this.numericResult = value;
    }

    /**
     * Gets the value of the resultReferenceRange property.
     * 
     * @return
     *     possible object is
     *     {@link ResultReferenceRange }
     *     
     */
    public ResultReferenceRange getResultReferenceRange() {
        return resultReferenceRange;
    }

    /**
     * Sets the value of the resultReferenceRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultReferenceRange }
     *     
     */
    public void setResultReferenceRange(ResultReferenceRange value) {
        this.resultReferenceRange = value;
    }

    /**
     * Gets the value of the resultUnits property.
     * 
     * @return
     *     possible object is
     *     {@link ResultUnits }
     *     
     */
    public ResultUnits getResultUnits() {
        return resultUnits;
    }

    /**
     * Sets the value of the resultUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultUnits }
     *     
     */
    public void setResultUnits(ResultUnits value) {
        this.resultUnits = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the resultClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultClass() {
        return resultClass;
    }

    /**
     * Sets the value of the resultClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultClass(String value) {
        this.resultClass = value;
    }

    /**
     * Gets the value of the resultType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultType() {
        return resultType;
    }

    /**
     * Sets the value of the resultType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultType(String value) {
        this.resultType = value;
    }

}
