//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.12 at 09:11:55 AM EDT 
//


package com.mapping.esource.fhirmapping.beans.gtp;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.mapping.esource.fhirmapping.util.DateTimeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ActualCollectionDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="PlannedCollectionTimeElapsed">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="9"/>
 *             &lt;pattern value="\d\d\d-([01]\d|2[0123])-[012345]\d"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PlannedCollectionTimeElapsedDescription">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CollectionEndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SpecimenCollection")
public class SpecimenCollection
    implements Serializable
{

    private final static long serialVersionUID = 5190875983846359311L;
    @XmlAttribute(name = "ActualCollectionDateTime", required = true)
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date actualCollectionDateTime;
    @XmlAttribute(name = "PlannedCollectionTimeElapsed")
    protected String plannedCollectionTimeElapsed;
    @XmlAttribute(name = "PlannedCollectionTimeElapsedDescription")
    protected String plannedCollectionTimeElapsedDescription;
    @XmlAttribute(name = "CollectionEndDateTime")
    @XmlJavaTypeAdapter(DateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Date collectionEndDateTime;

    /**
     * Gets the value of the actualCollectionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getActualCollectionDateTime() {
        return actualCollectionDateTime;
    }

    /**
     * Sets the value of the actualCollectionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualCollectionDateTime(Date value) {
        this.actualCollectionDateTime = value;
    }

    /**
     * Gets the value of the plannedCollectionTimeElapsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedCollectionTimeElapsed() {
        return plannedCollectionTimeElapsed;
    }

    /**
     * Sets the value of the plannedCollectionTimeElapsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedCollectionTimeElapsed(String value) {
        this.plannedCollectionTimeElapsed = value;
    }

    /**
     * Gets the value of the plannedCollectionTimeElapsedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedCollectionTimeElapsedDescription() {
        return plannedCollectionTimeElapsedDescription;
    }

    /**
     * Sets the value of the plannedCollectionTimeElapsedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedCollectionTimeElapsedDescription(String value) {
        this.plannedCollectionTimeElapsedDescription = value;
    }

    /**
     * Gets the value of the collectionEndDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getCollectionEndDateTime() {
        return collectionEndDateTime;
    }

    /**
     * Sets the value of the collectionEndDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionEndDateTime(Date value) {
        this.collectionEndDateTime = value;
    }

}
