//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.15 at 01:50:20 PM EDT 
//


package com.mapping.esource.fhirmapping.beans.gtp;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}ScreenID"/>
 *             &lt;element ref="{}SubjectID" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}SubjectID"/>
 *             &lt;element ref="{}ScreenID" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}SpareSubjectID" minOccurs="0"/>
 *         &lt;element ref="{}Sex" minOccurs="0"/>
 *         &lt;element ref="{}Race" minOccurs="0"/>
 *         &lt;element ref="{}Confidential" minOccurs="0"/>
 *         &lt;element ref="{}Visit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}TransactionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Subject")
public class Subject
    implements Serializable
{

    private final static long serialVersionUID = 5190875983846359311L;
    @XmlElementRefs({
        @XmlElementRef(name = "TransactionType", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SubjectID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Visit", type = Visit.class, required = false),
        @XmlElementRef(name = "ScreenID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SpareSubjectID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Race", type = Race.class, required = false),
        @XmlElementRef(name = "Sex", type = Sex.class, required = false),
        @XmlElementRef(name = "Confidential", type = Confidential.class, required = false)
    })
    protected List<Serializable> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "SubjectID" is used by two different parts of a schema. See: 
     * line 104 of file:/C:/LLY_Fuse/sqlLoader_workspace/dump/schema/LabResultsBaseSchema_V1_01.xsd
     * line 101 of file:/C:/LLY_Fuse/sqlLoader_workspace/dump/schema/LabResultsBaseSchema_V1_01.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sex }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Visit }
     * {@link Confidential }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Race }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
